### ISSUE TITLE
Solucionar el uso del submódulo Libft

### ISSUE THREAD

**Issue by Enuni5** [15Galan/gt_datalib#4]
En el [paso 03](https://github.com/15Galan/gt_datalib#03---el-subm%C3%B3dulo-libft) de la parte obligatoria, sería buena idea omitir la parte en la que se mueve el fichero .gitmodules a la carpeta del equipo y, para que no haya conflicto a la hora de hacer el pull request al final del taller, que se indique que hay que añadir este fichero a .gitignore.

**Comment by 15Galan** [comment]
¡Muchas gracias por la info! Lo marcaré como bug.

**Comment by 15Galan** [comment]
Tras reflexionar un poco la idea de **ignorar el fichero *.gimodules***, se presenta un problema, y es que se impide su disponibilidad para el resto de compañeros de un equipo.

Esto no se puede evitar de ninguna forma ya que, como se vió en el clúster durante el taller, se está obligando a que *.gitmodules* se encuentre en la raíz del repositorio, una zona común a todos los *forks* realizados y que presentaría conflictos en el último paso si todos los modifican.

Por otra parte, también había contemplado la idea de **añadir el submódulo de Libft a la raíz del proyecto** para que los equipos solo tengan que inicializarlo en futuras ediciones; no se cubriría la acción de *añadir un submódulo*, pero tampoco es tan relevante.

El fichero *.gitmodules* estaría en la raíz indicando que la carpeta Libft (también en la raíz) es un submódulo; cambiando las referencias en el código C se podría hacer que todos los equipos usaran esa librería de una forma cómún, en lugar de añadirla cada uno en su carpeta.

Esta última idea podría solventar los problemas anteriores:
- El fichero *.gitignore* necesita estar en la raíz.
- El fichero *.gitignore* no debe modificarse (más allá de ser creado).
- El submódulo Libft debe ser usado por todos los equipos.
